using Microsoft.Data.Sqlite;
using Npgsql;
using System.Data;

var options = ParseArgs(args);

var pgConnectionString = options.TryGetValue("pg", out var pg)
    ? pg
    : Environment.GetEnvironmentVariable("SUPABASE_DB_URL")
      ?? Environment.GetEnvironmentVariable("POSTGRES_CONNECTION_STRING")
      ?? Environment.GetEnvironmentVariable("ConnectionStrings__Supabase");

if (string.IsNullOrWhiteSpace(pgConnectionString))
{
    Console.Error.WriteLine("Missing Postgres connection string. Pass --pg \"...\" or set SUPABASE_DB_URL.");
    return 1;
}

var sqlitePath = options.TryGetValue("sqlite", out var sqlite)
    ? sqlite
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "shop.db"));

if (!File.Exists(sqlitePath))
{
    Console.Error.WriteLine($"SQLite file not found: {sqlitePath}");
    return 1;
}

Console.WriteLine($"SQLite source: {sqlitePath}");
Console.WriteLine("Connecting to Supabase Postgres...");

await using var sqliteConn = new SqliteConnection($"Data Source={sqlitePath}");
await sqliteConn.OpenAsync();

await using var pgConn = new NpgsqlConnection(pgConnectionString);
await pgConn.OpenAsync();

await using var tx = await pgConn.BeginTransactionAsync();

try
{
    await EnsureSchemaAsync(pgConn, tx);

    var tableOrder = new[]
    {
        "customers",
        "products",
        "orders",
        "order_items",
        "shipments",
        "product_reviews"
    };

    await TruncateAsync(pgConn, tx, tableOrder);

    foreach (var table in tableOrder)
    {
        var count = await CopyTableAsync(sqliteConn, pgConn, tx, table);
        Console.WriteLine($"Copied {count} rows into {table}");
    }

    await ResetSequencesAsync(pgConn, tx);

    await tx.CommitAsync();
    Console.WriteLine("Migration complete.");
    return 0;
}
catch (Exception ex)
{
    await tx.RollbackAsync();
    Console.Error.WriteLine("Migration failed:");
    Console.Error.WriteLine(ex.Message);
    return 1;
}

static Dictionary<string, string> ParseArgs(string[] args)
{
    var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    for (var i = 0; i < args.Length; i++)
    {
        if (!args[i].StartsWith("--", StringComparison.Ordinal))
        {
            continue;
        }

        var key = args[i][2..];
        var value = i + 1 < args.Length ? args[i + 1] : string.Empty;
        if (!value.StartsWith("--", StringComparison.Ordinal))
        {
            result[key] = value;
            i++;
        }
    }

    return result;
}

static async Task EnsureSchemaAsync(NpgsqlConnection conn, NpgsqlTransaction tx)
{
    var sql = @"
CREATE TABLE IF NOT EXISTS customers (
  customer_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name        TEXT NOT NULL,
  email            TEXT NOT NULL UNIQUE,
  gender           TEXT NOT NULL,
  birthdate        TEXT NOT NULL,
  created_at       TEXT NOT NULL,
  city             TEXT,
  state            TEXT,
  zip_code         TEXT,
  customer_segment TEXT,
  loyalty_tier     TEXT,
  is_active        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS products (
  product_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku          TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  category     TEXT NOT NULL,
  price        DOUBLE PRECISION NOT NULL,
  cost         DOUBLE PRECISION NOT NULL,
  is_active    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS orders (
  order_id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id        BIGINT NOT NULL REFERENCES customers(customer_id),
  order_datetime     TEXT NOT NULL,
  billing_zip        TEXT,
  shipping_zip       TEXT,
  shipping_state     TEXT,
  payment_method     TEXT NOT NULL,
  device_type        TEXT NOT NULL,
  ip_country         TEXT NOT NULL,
  promo_used         INTEGER NOT NULL DEFAULT 0,
  promo_code         TEXT,
  order_subtotal     DOUBLE PRECISION NOT NULL,
  shipping_fee       DOUBLE PRECISION NOT NULL,
  tax_amount         DOUBLE PRECISION NOT NULL,
  order_total        DOUBLE PRECISION NOT NULL,
  risk_score         DOUBLE PRECISION NOT NULL,
  is_fraud           INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS order_items (
  order_item_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id       BIGINT NOT NULL REFERENCES orders(order_id),
  product_id     BIGINT NOT NULL REFERENCES products(product_id),
  quantity       INTEGER NOT NULL,
  unit_price     DOUBLE PRECISION NOT NULL,
  line_total     DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS shipments (
  shipment_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id           BIGINT NOT NULL UNIQUE REFERENCES orders(order_id),
  ship_datetime      TEXT NOT NULL,
  carrier            TEXT NOT NULL,
  shipping_method    TEXT NOT NULL,
  distance_band      TEXT NOT NULL,
  promised_days      INTEGER NOT NULL,
  actual_days        INTEGER NOT NULL,
  late_delivery      INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_reviews (
  review_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id      BIGINT NOT NULL REFERENCES customers(customer_id),
  product_id       BIGINT NOT NULL REFERENCES products(product_id),
  rating           INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_datetime  TEXT NOT NULL,
  review_text      TEXT,
  UNIQUE(customer_id, product_id)
);

CREATE TABLE IF NOT EXISTS order_predictions (
  order_id                    BIGINT PRIMARY KEY REFERENCES orders(order_id),
  fraud_probability           DOUBLE PRECISION NOT NULL,
  predicted_fraud             INTEGER NOT NULL,
  prediction_timestamp        TEXT NOT NULL
);
";

    await using var cmd = new NpgsqlCommand(sql, conn, tx);
    await cmd.ExecuteNonQueryAsync();
}

static async Task TruncateAsync(NpgsqlConnection conn, NpgsqlTransaction tx, IEnumerable<string> tableOrder)
{
    var tables = string.Join(", ", tableOrder.Reverse().Select(t => $"\"{t}\""));
    var sql = $"TRUNCATE TABLE {tables} RESTART IDENTITY CASCADE;";
    await using var cmd = new NpgsqlCommand(sql, conn, tx);
    await cmd.ExecuteNonQueryAsync();
}

static async Task<int> CopyTableAsync(SqliteConnection sqliteConn, NpgsqlConnection pgConn, NpgsqlTransaction tx, string table)
{
    var columns = await ReadColumnsAsync(sqliteConn, table);

    var selectSql = $"SELECT {string.Join(", ", columns.Select(c => QuoteSqliteIdentifier(c)))} FROM {QuoteSqliteIdentifier(table)};";
    await using var select = new SqliteCommand(selectSql, sqliteConn);
    await using var reader = await select.ExecuteReaderAsync();

    if (columns.Count == 0)
    {
        return 0;
    }

    var insertSql = $"INSERT INTO \"{table}\" ({string.Join(", ", columns.Select(c => $"\"{c}\""))}) VALUES ({string.Join(", ", columns.Select((_, i) => $"@p{i}"))});";
    var rowCount = 0;

    while (await reader.ReadAsync())
    {
        await using var insert = new NpgsqlCommand(insertSql, pgConn, tx);
        for (var i = 0; i < columns.Count; i++)
        {
            var value = reader.IsDBNull(i) ? DBNull.Value : reader.GetValue(i);
            insert.Parameters.AddWithValue($"@p{i}", value);
        }

        await insert.ExecuteNonQueryAsync();
        rowCount++;
    }

    return rowCount;
}

static async Task<List<string>> ReadColumnsAsync(SqliteConnection sqliteConn, string table)
{
    var columns = new List<string>();
    await using var cmd = new SqliteCommand($"PRAGMA table_info({QuoteSqliteIdentifier(table)});", sqliteConn);
    await using var reader = await cmd.ExecuteReaderAsync();

    while (await reader.ReadAsync())
    {
        columns.Add(reader["name"]?.ToString() ?? string.Empty);
    }

    return columns.Where(c => !string.IsNullOrWhiteSpace(c)).ToList();
}

static async Task ResetSequencesAsync(NpgsqlConnection conn, NpgsqlTransaction tx)
{
    var seqColumns = new Dictionary<string, string>
    {
        ["customers"] = "customer_id",
        ["products"] = "product_id",
        ["orders"] = "order_id",
        ["order_items"] = "order_item_id",
        ["shipments"] = "shipment_id",
        ["product_reviews"] = "review_id"
    };

    foreach (var kvp in seqColumns)
    {
        var sql = $@"
SELECT setval(
    pg_get_serial_sequence('""{kvp.Key}""', '{kvp.Value}'),
    COALESCE((SELECT MAX(""{kvp.Value}"") FROM ""{kvp.Key}""), 1),
    (SELECT COUNT(*) > 0 FROM ""{kvp.Key}"")
);";

        await using var cmd = new NpgsqlCommand(sql, conn, tx);
        await cmd.ExecuteNonQueryAsync();
    }
}

static string QuoteSqliteIdentifier(string id)
{
    return $"\"{id.Replace("\"", "\"\"")}\"";
}
